version: '3.8'

services:
  backend:
    build: ./backend
    image: my-backend
    container_name: backend-container
    ports:
      - "5000:5000"
  

  frontend:
    build: ./nginx
    image: my-frontend
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend

