version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "5000"
  

  frontend:
    build: ./nginx
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

